---
title: "Untitled"
output: html_document
date: "2023-01-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(ggplot2)
con <- DBI::dbConnect(bigrquery::bigquery(), 
                      project = "world-fishing-827", 
                      use_legacy_sql = FALSE)
```


# CREATE DATE/AREA table and upload to BQ
```{r}
areas <- c('nw_indian','nw_pacific','se_pacific','sw_atlantic')
dates <- seq.Date(as.Date('2017-01-01'), as.Date('2020-12-31'),by = 'day')

date_areas <- expand.grid(areas, dates) 

date_areas %>%
  rename(area = Var1,
         date = Var2) %>%
  mutate(area = as.character(area)) %>%
  bigrquery::bq_table_upload(x = bigrquery::bq_table(project = "world-fishing-827", 
                                                       dataset = 'scratch_nate', 
                                                       table = 'all_dates_area_2017_2020'),
                             values = .)
```


# Setup

```{r}
library(ggplot2)
library(dplyr)

# Establish connection to BigQuery project
con <- DBI::dbConnect(
  drv = bigrquery::bigquery(),
  project = "world-fishing-827",
  use_legacy_sql = FALSE
)
options(scipen = 20)

round1000 <- function(x){
  round(x*(10^-6),3)*10^6
}


round0.1 <- function(x){
  round(x*10)/10
}
```


# GET VIIRS and AIS count

```{r}

# Extracting only VBDs with radiance greater than RAD_THRESHOLD
RAD_THRESHOLD <- 10

# Extracting only night loitering vessels with daily night loitering hours greater than NL_HOUR_THRESHOLD

NL_HOUR_THRESHOLD <- 1

# VIIRS-AIS matching with score greater than SCORE_THRESHOLD regarded as reliable matching
SCORE_THRESHOLD <- 0.01


# Get daily counts of VIIRS detentions and night loitering vessels
query <- glue::glue(readr::read_file(  here::here("queries", "05_viirs_for_seasonal_SI.sql")))



viirs_ais_counts_orig_df <-
  DBI::dbGetQuery(con, query) %>%
  mutate(
    score_threshold = SCORE_THRESHOLD,
    nl_threshold = NL_HOUR_THRESHOLD,
    rad_threshold = RAD_THRESHOLD
  )


# rds_file <- "viirs_ais_counts_for_paper.rds"
# saveRDS(viirs_ais_counts_orig_df, rds_file)
```


# eliminate anomaly date from counting data


```{r}
# eliminate anomaly date
viirs_ais_counts_df <-
  viirs_ais_counts_orig_df %>%
  rename(year_month0.5 = year_half_month) %>%
  filter(!(area == "se_pacific" & date == as.Date("2017-04-07")))


# check data after eliminating the anomaly date
# ggplot(viirs_ais_counts_df) +
#   geom_bar(aes(date, count_viirs_total),
#            stat = "identity",
#            width = 1) +
#   #geom_line(aes(date, count_viirs_total_halfmonth), width = 1)+
#   facet_wrap( ~ area) +
#   ggsave(
#     "viirs_ais_counts_df.png",
#     width = 20,
#     height = 20,
#     units = "cm"
#   )
```


# Extract the date when the maximum number of VIIRS detections was observed every 15 days.


```{r}

#########################
# Extract AIS/VIIRS on the date where maximum VIIRS are observed for each 15 days
suppressWarnings(
  viirs_ais_on_15days_max_df <-
    viirs_ais_counts_df %>%
    group_by(year_month0.5, area) %>%
    mutate(max_count_half_month = max(count_viirs_total, na.rm = TRUE)) %>%
    filter(count_viirs_total == max_count_half_month) %>%
    arrange(area, date) %>%
    mutate(rownum = row_number()) %>%
    filter(rownum == 1)
)

# Change column name and select only necessary columns
viirs_ais_half_month_df <-
  viirs_ais_on_15days_max_df %>%
  rename(
    count_viirs_total_half_month = count_viirs_total,
    count_viirs_matched_half_month = count_viirs_matched,
    # count night loitering vessels
    count_nl_half_month = count_nl,
    count_nl_matched_half_month = count_nl_matched,
  ) %>%
  select(
    area,
    year_month0.5,
    count_viirs_total_half_month,
    count_viirs_matched_half_month,
    count_nl_half_month,
    count_nl_matched_half_month,
  ) %>%
  arrange(area, year_month0.5)

# Join 15-day max count to every day count
viirs_ais_counts_daily_month0.5_df <-
  viirs_ais_counts_df %>%
  left_join(viirs_ais_half_month_df, by = c("area", "year_month0.5"))
```

```{r}

yearly_area_long_df <-
  viirs_ais_counts_daily_month0.5_df %>%
  mutate(
    #estimated_total_vessels = estimated_total_vessels_month6,
    total_viirs = count_viirs_total_half_month,
    #total_ais = count_nl_half_month,
    viirs_ais_matched = count_nl_matched_half_month,
    only_viirs = total_viirs - viirs_ais_matched,
    #only_ais = total_ais - viirs_ais_matched,
    #total_ais_viirs = viirs_ais_matched + only_viirs + only_ais,
  ) %>%
  mutate(
    area = case_when(
      area == "nw_indian" ~ "NW Indian",
      area == "nw_pacific" ~ "NW Pacific",
      area == "se_pacific" ~ "SE Pacific",
      area == "sw_atlantic" ~ "SW Atlantic"
    )
  ) %>%
  # mutate(only_estimate =
  #          ifelse(
  #            estimated_total_vessels > total_ais_viirs,
  #            round(estimated_total_vessels - total_ais_viirs),
  #            0
  #          )) %>%
  select(date,
         area,
         only_viirs,
         #only_ais,
         viirs_ais_matched,
         #only_estimate,
         ) %>%
  tidyr::pivot_longer(
    cols = c(only_viirs,
             #only_ais,
             viirs_ais_matched,
             #only_estimate
             ),
    names_to = "Source",
    values_to = "Vessel count",
    ) %>% 
   mutate(Source = factor(Source, levels = rev(c(
     "viirs_ais_matched",
     #"only_ais",
     "only_viirs"
     #"only_estimate"
   )))) %>%
  mutate(`Vessel count` = ifelse(is.na(`Vessel count`), 0, `Vessel count`)) %>%
  mutate(
    Source = case_when(
      Source == "viirs_ais_matched" ~ "Detected by both VIIRS and AIS",
      #Source == "only_ais" ~ "Detected only by AIS",
      Source == "only_viirs" ~ "Detected only by VIIRS"
      #Source == "only_estimate" ~ "Potentially undetected vessels"
    )
  ) %>% 
  mutate(Source = factor(
    Source,
    levels = c("Detected by both VIIRS and AIS",
               "Detected only by VIIRS"
               #"Potentially undetected vessels",
               #"Detected only by AIS"
               )
    )) %>% 
  mutate(`Detection type` = Source) %>%
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         month_year = as.Date(glue::glue('{year}-{month}-15'))) %>%
  group_by(area, month_year, Source) %>%
  summarise(`Vessel count` = sum(`Vessel count`, na.rm = TRUE)) #%>%
  # group_by(area, year) %>%
  # mutate(total = sum(`Vessel count`, na.rm = TRUE),
  #        percentage = round(100 * (`Vessel count` / total))) %>%
  # mutate(percentage_display = ifelse(
  #   Source == "Detected by both VIIRS and AIS",
  #   "",
  #   paste0(percentage, "%")
  #)
#)
               
               
(plot <-           
ggplot(yearly_area_long_df) +
  geom_col(aes(month_year, `Vessel count`, fill = Source)) +
  # geom_text(aes(x = year, y = `Vessel count` * 0.5, label = percentage_display),
  #           size = 2) +
  fishwatchr::theme_gfw() +
  facet_wrap(area ~ ., strip.position = "top") +
  #xlim(as.Date("2017-01-01"), as.Date("2021-12-31")) +
  scale_fill_manual(
    values = c(
      #"only_ais" = "blue",
      "Detected only by VIIRS" = fishwatchr::gfw_palette("chart")[6],
      "Detected by both VIIRS and AIS" = fishwatchr::gfw_palette("chart")[1]
      #"only_estimate" = "gray"
    )
  ) +
  #scale_x_date(breaks = seq.Date(as.Date("2017-01-01"), as.Date("2021-01-01"), by = "year"), labels = seq(2017,2021,by=1))+
  xlab("Year") +
  ylab("Vessel days") +
  theme(legend.position="bottom") 
)

ggsave(
  filename = here::here('outputs','figures','VIIRS','Figure_S7_viirs_seasonal_matching_by_region.png'),
  plot = plot,
  width = 20,
  height = 15,
  units = "cm",
  dpi = 600
)
```




